/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minprojet1;

/**
 *
 * @author mmars
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_intro = new javax.swing.JLabel();
        up1 = new javax.swing.JButton();
        up2 = new javax.swing.JButton();
        up3 = new javax.swing.JButton();
        up4 = new javax.swing.JButton();
        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        nombre4 = new javax.swing.JLabel();
        down1 = new javax.swing.JButton();
        down2 = new javax.swing.JButton();
        down3 = new javax.swing.JButton();
        down4 = new javax.swing.JButton();
        test = new javax.swing.JButton();
        text_exact = new javax.swing.JLabel();
        nombre_exact = new javax.swing.JLabel();
        text_haut = new javax.swing.JLabel();
        nombre_haut = new javax.swing.JLabel();
        text_bas = new javax.swing.JLabel();
        nombre_bas = new javax.swing.JLabel();
        text_score = new javax.swing.JLabel();
        butoon_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_intro.setText("SALUT! A toi de trouver le code en 10 tentatives");
        getContentPane().add(text_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 44, -1, -1));

        up1.setText("/\\");
            up1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up1ActionPerformed(evt);
                }
            });
            getContentPane().add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 70, -1));

            up2.setText("/\\");
                getContentPane().add(up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, -1));

                up3.setText("/\\");
                    getContentPane().add(up3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, -1));

                    up4.setText("/\\");
                        getContentPane().add(up4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 70, -1));

                        nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nombre1.setText("jLabel1");
                        nombre1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 146, 70, 120));

                        nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nombre2.setText("jLabel2");
                        nombre2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 146, 70, 120));

                        nombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nombre3.setText("jLabel3");
                        nombre3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 146, 70, 120));

                        nombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nombre4.setText("jLabel4");
                        nombre4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        getContentPane().add(nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 146, 70, 120));

                        down1.setText("\\/");
                        getContentPane().add(down1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 70, -1));

                        down2.setText("\\/");
                        down2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 70, -1));

                        down3.setText("\\/");
                        getContentPane().add(down3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 70, -1));

                        down4.setText("\\/");
                        getContentPane().add(down4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, -1));

                        test.setText("Tester");
                        test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                testActionPerformed(evt);
                            }
                        });
                        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

                        text_exact.setText("jLabel1");
                        getContentPane().add(text_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

                        nombre_exact.setText("jLabel1");
                        getContentPane().add(nombre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

                        text_haut.setText("jLabel1");
                        getContentPane().add(text_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

                        nombre_haut.setText("jLabel2");
                        getContentPane().add(nombre_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

                        text_bas.setText("jLabel3");
                        getContentPane().add(text_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

                        nombre_bas.setText("jLabel4");
                        getContentPane().add(nombre_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

                        text_score.setText("jLabel2");
                        getContentPane().add(text_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

                        butoon_recommencer.setText("Recommencer");
                        butoon_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                butoon_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(butoon_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up1ActionPerformed

    private void down2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down2ActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testActionPerformed

    private void butoon_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoon_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butoon_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butoon_recommencer;
    private javax.swing.JButton down1;
    private javax.swing.JButton down2;
    private javax.swing.JButton down3;
    private javax.swing.JButton down4;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre4;
    private javax.swing.JLabel nombre_bas;
    private javax.swing.JLabel nombre_exact;
    private javax.swing.JLabel nombre_haut;
    private javax.swing.JButton test;
    private javax.swing.JLabel text_bas;
    private javax.swing.JLabel text_exact;
    private javax.swing.JLabel text_haut;
    private javax.swing.JLabel text_intro;
    private javax.swing.JLabel text_score;
    private javax.swing.JButton up1;
    private javax.swing.JButton up2;
    private javax.swing.JButton up3;
    private javax.swing.JButton up4;
    // End of variables declaration//GEN-END:variables
}
